### ISSUE TITLE
Authorization Failure

### ISSUE THREAD

**Issue by bradmartin** [drrasic/ionic_twitter_feed#1]
I followed this code and I can't determine why the authorization is failing. 
![twitauth](https://cloud.githubusercontent.com/assets/6006148/8145127/f08d8f70-11c0-11e5-96cf-80e66c028250.JPG)

I have the correct keys in place and running on an actual device. Is there anything you might have left out of the docs or config?

**Comment by drrasic** [comment]
Eveything is there, i have tested it just by pulling this rep, switching the keys and running, and it worked perfectly... I'll try to recreate that error tonight and possibly help.

**Comment by bradmartin** [comment]
I'm trying to diagnose it, I've debugged the factory calls and everything goes through, the keys are in place. I'll check to make sure they're correct tonight. I'll pull this repo now and use my keys and see if my keys work correctly. Thanks. This solution is one of the simplest I've found with Twitter 1.1 API.

**Comment by bradmartin** [comment]
![ionictwit](https://cloud.githubusercontent.com/assets/6006148/8145909/9545b662-11e1-11e5-83ab-b17266461b58.JPG)

I downloaded the repo, put my keys in the services variables and built the .apk. Installed and that's the errors when using chrome://inspect in the console. I'll work on it for a little bit longer and see what I can find. I'm trying to pause it to debug why the token isn't available in the call. I'll move the call to a button click and see if I can find something useful to you.

**Comment by bradmartin** [comment]
Somewhere authorization and access_token are null. Stepping through it now to see if I can wrap my head around the Oauth process they have.

**Comment by bradmartin** [comment]
I've been testing it with POSTMAN to see what's off. I think the 'grant_type=client_credentials' is not being sent in the request correctly. When testing the request in POSTMAN, I had to select the 'x-www-form-urlencoded' option for the 'grant_type=client_credentials' then the token is returned. If I try passing as 'form-data' it returns code 170 from Twitter api : 'Missing required parameter: 'grant_type'

**Comment by drrasic** [comment]
Yeah, thats why there is 'application/x-www-form-urlencoded' in post method on line 138. It doesn't work without that. 

I did some tests to try and produce the exact same output but was unable... so to clear some possibilites i have made a test acc on twitter that is working for me, so ill email you the keys to test out. Im interested in how it goes...

**Comment by drrasic** [comment]
Oh man it's the f*****g new cordova version :), i forgot about this.... and i had and older version installed on this system...
take a look at this
http://docs.ionic.io/v1.0/docs/cordova-whitelist

For quick test u need to 
cordova plugin add https://github.com/apache/cordova-plugin-whitelist

and this meta tag to index.html
`<meta http-equiv="Content-Security-Policy" content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval'">`

Hope it helps.

**Comment by bradmartin** [comment]
haha I have the plugin already, I just don't have the meta tag. I'll add it and give it a try later on. Thanks!
