### ISSUE TITLE
Real API keys included in directives.js

### ISSUE THREAD

**Issue by ChrisHartley** [drrasic/ionic_twitter_feed#3]
It looks like you inadvertently included your own API keys in directives.js - and I don't think directives.js is used anyway. Best to invalidate those keys.

**Comment by drrasic** [comment]
Thanks, looks like i commited directives.js by accident.
Btw those keys can be found by looking thru commit history if someone really wanted them, i made them just for this demo so i dont care much. But ill invalidate them now that im on it, so if someone was using them, its on you :D
